#!/bin/bash
set -e

PERSISTENT=/mnt/wp-content

# Setup symlink BEFORE WordPress entrypoint runs
if [ -d "$PERSISTENT" ]; then
    if [ -e /var/www/html/wp-content ] && [ ! -L /var/www/html/wp-content ]; then
        rm -rf /var/www/html/wp-content
    fi
    ln -sf "$PERSISTENT" /var/www/html/wp-content
fi

# Remove Redis object cache
rm -f /mnt/wp-content/object-cache.php

# Patch docker-entrypoint.sh to always set correct table prefix
# This ensures it's set AFTER wp-config.php is generated by WordPress
sed -i "s/\\\$table_prefix = getenv_docker('WORDPRESS_TABLE_PREFIX', 'wp_');/\\\$table_prefix = 'a6_';/" \
    /usr/local/bin/docker-entrypoint.sh 2>/dev/null || true

# Run original WordPress entrypoint
exec docker-entrypoint.sh "$@"
